import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Bell, Eye, Minus, TrendingUp } from 'lucide-react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import DashboardLayout from '../layouts/DashboardLayout';
import Button from '../components/Button';
import Modal from '../components/Modal';

const prices = [
  { name: 'Tomato', category: 'Vegetables', market: 'Coimbatore Market', min: 20, max: 35, modal: 28, yesterday: 26, arrival: 1200, farmer: 32, buyer: 30, trend: [25, 26, 27, 26, 27, 26, 28], markets: { Coimbatore: 28, Pollachi: 31, Tiruppur: 29, Mettupalayam: 30 } },
  { name: 'Onion', category: 'Vegetables', market: 'Coimbatore Market', min: 30, max: 42, modal: 36, yesterday: 37, arrival: 950, farmer: 38, buyer: 35, trend: [35, 36, 36, 37, 38, 37, 36], markets: { Coimbatore: 36, Pollachi: 34, Tiruppur: 35, Mettupalayam: 33 } },
  { name: 'Potato', category: 'Vegetables', market: 'Coimbatore Market', min: 25, max: 34, modal: 30, yesterday: 29, arrival: 700, farmer: 32, buyer: 31, trend: [28, 29, 28, 29, 30, 29, 30], markets: { Coimbatore: 30, Pollachi: 29, Tiruppur: 32, Mettupalayam: 31 } },
  { name: 'Carrot', category: 'Vegetables', market: 'Coimbatore Market', min: 38, max: 52, modal: 45, yesterday: 45, arrival: 450, farmer: 46, buyer: 44, trend: [42, 43, 44, 45, 44, 45, 45], markets: { Coimbatore: 45, Pollachi: 43, Tiruppur: 44, Mettupalayam: 48 } },
  { name: 'Green Chilli', category: 'Spices', market: 'Coimbatore Market', min: 65, max: 85, modal: 76, yesterday: 68, arrival: 260, farmer: 80, buyer: 78, trend: [65, 68, 70, 72, 71, 74, 76], markets: { Coimbatore: 76, Pollachi: 82, Tiruppur: 79, Mettupalayam: 75 } },
  { name: 'Cabbage', category: 'Vegetables', market: 'Coimbatore Market', min: 18, max: 26, modal: 22, yesterday: 24, arrival: 580, farmer: 25, buyer: 21, trend: [25, 24, 24, 23, 23, 24, 22], markets: { Coimbatore: 22, Pollachi: 24, Tiruppur: 21, Mettupalayam: 23 } },
];

const dates = ['5 Sep', '6 Sep', '7 Sep', '8 Sep', '9 Sep', '10 Sep', '11 Sep'];
const money = (value) => `₹${value.toLocaleString('en-IN')}`;
const difference = (item) => item.modal - item.yesterday;
const movement = (item) => difference(item) > 0 ? 'up' : difference(item) < 0 ? 'down' : 'stable';
const trendData = (item) => item.trend.map((price, index) => ({ date: dates[index], price }));

const TrendChart = ({ item }) => (
  <ResponsiveContainer width="100%" height={190}>
    <LineChart data={trendData(item)}><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis hide /><Tooltip formatter={(value) => [`₹${value}/KG`, 'Price']} /><Line type="monotone" dataKey="price" stroke="#1d6f42" strokeWidth={3} dot={{ r: 3 }} /></LineChart>
  </ResponsiveContainer>
);

const MarketIntelligencePage = ({ role = 'FPO', title = 'Market Intelligence' }) => {
  const isFarmer = role === 'farmer';
  const categories = [...new Set(prices.map((item) => item.category))];
  const [filters, setFilters] = useState({ search: '', category: '', market: '', movement: '', sort: 'default' });
  const [selectedName, setSelectedName] = useState('Tomato');
  const [details, setDetails] = useState(null);
  const [alerts, setAlerts] = useState([]);
  const [alert, setAlert] = useState({ vegetable: 'Tomato', target: '35', direction: 'above' });
  const selected = prices.find((item) => item.name === selectedName) || prices[0];
  const setFilter = (name, value) => setFilters((current) => ({ ...current, [name]: value }));
  const filtered = useMemo(() => prices.filter((item) => {
    const query = filters.search.toLowerCase();
    return [item.name, item.market, item.category].some((value) => value.toLowerCase().includes(query)) && (!filters.category || item.category === filters.category) && (!filters.market || item.market === filters.market) && (!filters.movement || movement(item) === filters.movement);
  }).sort((a, b) => filters.sort === 'high' ? b.modal - a.modal : filters.sort === 'low' ? a.modal - b.modal : filters.sort === 'increase' ? difference(b) - difference(a) : filters.sort === 'decrease' ? difference(a) - difference(b) : filters.sort === 'arrival' ? b.arrival - a.arrival : 0), [filters]);
  const average = Math.round(prices.reduce((sum, item) => sum + item.modal, 0) / prices.length);
  const bestMarkets = prices.map((item) => { const best = Object.entries(item.markets).sort((a, b) => b[1] - a[1])[0]; return { ...item, bestMarket: best[0], bestPrice: best[1] }; }).sort((a, b) => b.bestPrice - a.bestPrice).slice(0, 4);
  const comparison = Object.entries(selected.markets);
  const highestMarketPrice = Math.max(...comparison.map(([, value]) => value));
  const lowestMarketPrice = Math.min(...comparison.map(([, value]) => value));
  const saveAlert = (event) => { event.preventDefault(); setAlerts((current) => [...current, { ...alert, id: Date.now() }]); };

  return (
    <DashboardLayout role={role} title={title}>
      <div className="market-page">
        <section className="section-block market-overview">
          <div><span className="eyebrow">Market Intelligence</span><h2>Today's Market Prices</h2><p className="market-date">11 September 2026</p></div><span className="pill-tag">Demo Data</span>
          <div className="market-overview-grid"><div><span>State</span><strong>Tamil Nadu</strong></div><div><span>District</span><strong>Coimbatore</strong></div><div><span>Selected Market</span><strong>Coimbatore Market</strong></div><div><span>Last Updated</span><strong>10:30 AM</strong></div><div><span>Market Status</span><strong className="market-active">Active</strong></div><div><span>Data Source</span><strong>Demo Data - API pending</strong></div></div>
        </section>
        <section className="stats-grid market-summary-cards">{[['Vegetables Tracked', prices.length], ['Average Price', `${money(average)}/KG`], ['Highest Price', `${money(Math.max(...prices.map((item) => item.modal)))}/KG`], ['Lowest Price', `${money(Math.min(...prices.map((item) => item.modal)))}/KG`], ['Biggest Increase', `+${Math.max(...prices.map((item) => difference(item) / item.yesterday * 100)).toFixed(1)}%`], ['Biggest Decrease', `${Math.min(...prices.map((item) => difference(item) / item.yesterday * 100)).toFixed(1)}%`]].map(([label, value]) => <div className="stat-card" key={label}><div className="stat-card__header"><span className="stat-card__dot stat-card__dot--green" />{label}</div><div className="stat-card__value">{value}</div></div>)}</section>
        <section className="section-block market-table-section">
          <div className="section-header"><div><h3>Today's Vegetable Prices</h3><p className="muted-text">Demo Data - Connect market-price API for live data. Updated 10:30 AM.</p></div></div>
          <div className="market-filters"><label className="produce-search"><input placeholder="Search vegetable, market or category" value={filters.search} onChange={(event) => setFilter('search', event.target.value)} /></label><select value={filters.category} onChange={(event) => setFilter('category', event.target.value)}><option value="">All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><select value={filters.market} onChange={(event) => setFilter('market', event.target.value)}><option value="">All markets</option><option>Coimbatore Market</option><option>Pollachi Market</option><option>Tiruppur Market</option></select><select value={filters.movement} onChange={(event) => setFilter('movement', event.target.value)}><option value="">All movements</option><option value="up">Increased</option><option value="down">Decreased</option><option value="stable">Stable</option></select><select value={filters.sort} onChange={(event) => setFilter('sort', event.target.value)}><option value="default">Sort prices</option><option value="high">Highest price</option><option value="low">Lowest price</option><option value="increase">Biggest increase</option><option value="decrease">Biggest decrease</option><option value="arrival">Highest arrival</option></select></div>
          <div className="table-wrap"><table className="data-table market-price-table"><thead><tr><th>Vegetable</th><th>Category</th><th>Market</th><th>Min/KG</th><th>Max/KG</th><th>Modal/KG</th><th>Yesterday</th><th>Change</th><th>Arrival</th><th>Updated</th><th>Action</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{item.market}</td><td>{money(item.min)}</td><td>{money(item.max)}</td><td><strong>{money(item.modal)}</strong></td><td>{money(item.yesterday)}</td><td><span className={`price-movement price-movement--${movement(item)}`}>{difference(item) > 0 ? <ArrowUp size={14} /> : difference(item) < 0 ? <ArrowDown size={14} /> : <Minus size={14} />}{difference(item) > 0 ? '+' : ''}{money(difference(item))} ({(difference(item) / item.yesterday * 100).toFixed(1)}%)</span></td><td>{item.arrival.toLocaleString()} KG</td><td>10:30 AM</td><td><Button variant="ghost" onClick={() => setDetails(item)}><Eye size={15} /> View Details</Button></td></tr>)}</tbody></table></div>
        </section>
        <div className="market-two-column"><section className="section-block"><div className="section-header"><div><h3>7-Day Price Trend</h3><p className="muted-text">Last 7 days of demo market movement.</p></div><select value={selectedName} onChange={(event) => setSelectedName(event.target.value)}>{prices.map((item) => <option key={item.name}>{item.name}</option>)}</select></div><h4 className="market-subheading">{selected.name} Price Trend</h4><TrendChart item={selected} /><div className="trend-stat-row"><span>Lowest {money(Math.min(...selected.trend))}</span><span>Average {money(Math.round(selected.trend.reduce((a, b) => a + b, 0) / selected.trend.length))}</span><span>Highest {money(Math.max(...selected.trend))}</span></div></section><section className="section-block"><div className="section-header"><div><h3>Compare Market Prices</h3><p className="muted-text">Highest current market is highlighted.</p></div></div><select className="market-wide-select" value={selectedName} onChange={(event) => setSelectedName(event.target.value)}>{prices.map((item) => <option key={item.name}>{item.name}</option>)}</select><div className="comparison-list">{comparison.map(([market, value]) => <div className={value === highestMarketPrice ? 'comparison-row comparison-row--best' : 'comparison-row'} key={market}><span>{market}</span><strong>{money(value)}/KG</strong></div>)}</div><div className="comparison-summary"><span>Highest {money(highestMarketPrice)}</span><span>Lowest {money(lowestMarketPrice)}</span><span>Difference {money(highestMarketPrice - lowestMarketPrice)}</span></div></section></div>
        {isFarmer && <div className="market-two-column"><section className="section-block"><div className="section-header"><div><h3>My Price vs Market Price</h3><p className="muted-text">Your selling price stays separate from the market reference.</p></div></div><div className="price-compare-card"><span>Product: <strong>{selected.name}</strong></span><div><div><small>Your Selling Price</small><strong>{money(selected.farmer)}/KG</strong></div><div><small>Today's Market Price</small><strong>{money(selected.modal)}/KG</strong></div></div><p>Your price is {money(Math.abs(selected.farmer - selected.modal))}/KG {selected.farmer >= selected.modal ? 'above' : 'below'} the current market price.</p></div></section><section className="section-block"><div className="section-header"><div><h3>Market Price vs Buyer Offer</h3><p className="muted-text">Compare market, farmer, and buyer prices.</p></div></div><div className="offer-compare-grid"><div><span>Market Price</span><strong>{money(selected.modal)}/KG</strong></div><div><span>Farmer's Price</span><strong>{money(selected.farmer)}/KG</strong></div><div><span>Buyer Offer</span><strong>{money(selected.buyer)}/KG</strong></div></div><div className="comparison-summary"><span>Offer vs Market {selected.buyer - selected.modal >= 0 ? '+' : ''}{money(selected.buyer - selected.modal)}/KG</span><span>Offer vs Farmer {selected.buyer - selected.farmer >= 0 ? '+' : ''}{money(selected.buyer - selected.farmer)}/KG</span></div></section></div>}
        <div className="market-two-column"><section className="section-block"><div className="section-header"><div><h3>Set Price Alert</h3><p className="muted-text">Notify me when a price reaches a target.</p></div><Bell size={21} /></div><form className="alert-form" onSubmit={saveAlert}><select value={alert.vegetable} onChange={(event) => setAlert({ ...alert, vegetable: event.target.value })}>{prices.map((item) => <option key={item.name}>{item.name}</option>)}</select><select value={alert.direction} onChange={(event) => setAlert({ ...alert, direction: event.target.value })}><option value="above">goes above</option><option value="below">goes below</option></select><input min="1" type="number" value={alert.target} onChange={(event) => setAlert({ ...alert, target: event.target.value })} /><Button type="submit">Set Price Alert</Button></form>{alerts.map((item) => <div className="saved-alert" key={item.id}><Bell size={15} /> {item.vegetable} {item.direction} ₹{item.target}/KG <span>Active</span></div>)}</section><section className="section-block"><div className="section-header"><div><h3>Market Arrivals</h3><p className="muted-text">Quantity reported in the selected market.</p></div></div><div className="arrival-list">{[...prices].sort((a, b) => b.arrival - a.arrival).map((item, index, list) => <div className="arrival-row" key={item.name}><span>{item.name}</span><div><span style={{ width: `${Math.max(18, item.arrival / list[0].arrival * 100)}%` }} /></div><strong>{item.arrival.toLocaleString()} KG</strong></div>)}</div></section></div>
        <section className="section-block"><div className="section-header"><div><h3>Best Current Market Opportunities</h3><p className="muted-text">Higher prices across available demo markets.</p></div><TrendingUp size={21} /></div><div className="opportunity-grid">{bestMarkets.map((item) => <div className="opportunity-market-card" key={item.name}><strong>{item.name}</strong><span>Best Market: {item.bestMarket}</span><b>{money(item.bestPrice)}/KG</b></div>)}</div></section>
      </div>
      <Modal isOpen={Boolean(details)} onClose={() => setDetails(null)} title={`${details?.name || ''} Price Details`}>{details && <div className="market-detail-modal"><div className="market-detail-heading"><div><span className="eyebrow">{details.category}</span><h3>{details.name}</h3><span className="muted-text">{details.market}, Coimbatore, Tamil Nadu</span></div><span className={`price-movement price-movement--${movement(details)}`}>{(difference(details) / details.yesterday * 100).toFixed(1)}%</span></div><div className="market-detail-grid"><div><span>Today's minimum</span><strong>{money(details.min)}/KG</strong></div><div><span>Today's maximum</span><strong>{money(details.max)}/KG</strong></div><div><span>Modal price</span><strong>{money(details.modal)}/KG</strong></div><div><span>Yesterday's price</span><strong>{money(details.yesterday)}/KG</strong></div><div><span>7-day average</span><strong>{money(Math.round(details.trend.reduce((a, b) => a + b, 0) / details.trend.length))}/KG</strong></div><div><span>30-day average</span><strong>{money(details.modal)}/KG</strong></div><div><span>Today's change</span><strong>{money(difference(details))}/KG</strong></div><div><span>Market arrival</span><strong>{details.arrival.toLocaleString()} KG</strong></div><div><span>Last updated</span><strong>10:30 AM</strong></div><div><span>Data source</span><strong>Demo Data</strong></div></div><TrendChart item={details} /></div>}</Modal>
    </DashboardLayout>
  );
};

export default MarketIntelligencePage;
