import { Bell, MapPin, Search, ShoppingCart, Truck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import Button from '../../components/Button';
import StatCard from '../../components/StatCard';
import { useBuyerStore } from '../../hooks/useBuyerStore';

const BuyerDashboard = () => {
  const navigate = useNavigate();
  const { products, orders, cart, notifications, addToCart } = useBuyerStore();
  const activeOrders = orders.filter((order) => !['Delivered', 'Cancelled'].includes(order.status)).length;
  const completedOrders = orders.filter((order) => order.status === 'Delivered').length;
  return <DashboardLayout role="buyer" title="Buyer Dashboard">
    <section className="buyer-welcome"><div><span className="eyebrow">Buyer workspace</span><h2>Welcome, Hotel Buyer</h2><p>Source fresh produce directly from trusted farmers across Tamil Nadu.</p></div><label className="buyer-home-search"><Search size={17} /><input placeholder="Search vegetables, farmers or products..." onKeyDown={(event) => event.key === 'Enter' && navigate('/buyer/products')} /></label></section>
    <div className="buyer-quick-actions"><Button onClick={() => navigate('/buyer/products')}><Search size={16} /> Browse Products</Button><Button variant="secondary" onClick={() => navigate('/buyer/orders')}><Truck size={16} /> My Orders</Button><Button variant="secondary" onClick={() => navigate('/buyer/cart')}><ShoppingCart size={16} /> My Cart</Button><Button variant="secondary" onClick={() => navigate('/buyer/requests')}><Bell size={16} /> My Requests</Button></div>
    <section className="stats-grid"><StatCard title="Total Orders" value={orders.length} subtitle="All time demo orders" accent="green" /><StatCard title="Active Orders" value={activeOrders} subtitle="Moving through delivery" accent="teal" /><StatCard title="Pending Orders" value={orders.filter((order) => ['Order Placed', 'Confirmed'].includes(order.status)).length} subtitle="Awaiting fulfilment" accent="amber" /><StatCard title="Completed Orders" value={completedOrders} subtitle="Delivered successfully" accent="dark" /><StatCard title="Cart Items" value={cart.reduce((sum, item) => sum + item.quantity, 0)} subtitle="Ready for checkout" accent="green" /></section>
    <section className="section-block"><div className="section-header"><div><h3>Recommended Products</h3><p className="muted-text">Fresh listings with clear farmer and market pricing.</p></div><button className="text-button" onClick={() => navigate('/buyer/products')}>Browse all</button></div><div className="buyer-recommendation-grid">{products.slice(0, 4).map((product) => <article className="buyer-recommendation" key={product.id}><img src={product.image} alt={product.name} /><div><strong>{product.name}</strong><span>{product.farmer} · <MapPin size={12} /> {product.location}</span><span>{product.quantity} KG available</span><div><b>₹{product.price}/KG</b><small>Market ₹{product.marketPrice}/KG</small></div><Button onClick={() => addToCart(product)}><ShoppingCart size={14} /> Add to Cart</Button></div></article>)}</div></section>
    <div className="two-column-grid"><section className="section-block"><div className="section-header"><h3>Recent Orders</h3><button className="text-button" onClick={() => navigate('/buyer/orders')}>View all</button></div><div className="buyer-order-list">{orders.slice(0, 3).map((order) => <div className="buyer-order-row" key={order.id}><div><strong>{order.id}</strong><span>{order.product} · {order.quantity} KG · {order.farmer}</span></div><div><span className={`delivery-status delivery-status--${order.status.toLowerCase().replaceAll(' ', '-')}`}>{order.status}</span><small>Expected {order.expected}</small></div><button className="text-button" onClick={() => navigate('/buyer/track')}>Track</button></div>)}</div></section><section className="section-block"><div className="section-header"><h3>Notifications</h3><button className="text-button" onClick={() => navigate('/buyer/notifications')}>View all</button></div><div className="buyer-notification-preview">{notifications.slice(0, 3).map((item) => <div key={item.id} className={item.unread ? 'buyer-notification-preview--unread' : ''}><Bell size={15} /><div><strong>{item.title}</strong><span>{item.message}</span><small>{item.time}</small></div></div>)}</div></section></div>
    <section className="section-block"><div className="section-header"><div><h3>Today's Market Prices</h3><p className="muted-text">Demo Market Data · reference values only.</p></div><button className="text-button" onClick={() => navigate('/buyer/prices')}>View market prices</button></div><div className="buyer-price-table"><div><strong>Vegetable</strong><strong>Market Price/KG</strong><strong>Change</strong><strong>Last Updated</strong></div>{products.slice(0, 4).map((product, index) => <div key={product.id}><span>{product.name}</span><strong>₹{product.marketPrice}/KG</strong><span className={index % 2 ? 'price-movement price-movement--down' : 'price-movement price-movement--up'}>{index % 2 ? '-2.1%' : '+4.4%'}</span><span>Today, 10:30 AM</span></div>)}</div></section>
  </DashboardLayout>;
};

export default BuyerDashboard;
