import { useMemo, useState } from 'react';
import { Check, Edit3, MapPin, PackageCheck, Pencil, Truck } from 'lucide-react';
import DashboardLayout from '../../layouts/DashboardLayout';
import Button from '../../components/Button';
import Modal from '../../components/Modal';

const initialProfile = {
  name: 'Dhiya S', phone: '+91 98765 43210', email: 'farmer@example.com', farmName: 'Green Valley Farm',
  location: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', farmerId: 'FARM1001', memberSince: 'January 2026',
};

const initialProducts = [
  { id: 1, name: 'Tomato', category: 'Vegetables', quantity: 500, price: 35, status: 'Available', location: 'Coimbatore', updated: 'Today', image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=640&q=80' },
  { id: 2, name: 'Potato', category: 'Vegetables', quantity: 750, price: 32, status: 'Available', location: 'Coimbatore', updated: 'Today', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=640&q=80' },
  { id: 3, name: 'Onion', category: 'Vegetables', quantity: 300, price: 40, status: 'Low Stock', location: 'Coimbatore', updated: 'Yesterday', image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=640&q=80' },
  { id: 4, name: 'Carrot', category: 'Vegetables', quantity: 200, price: 45, status: 'Available', location: 'Coimbatore', updated: 'Today', image: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?auto=format&fit=crop&w=640&q=80' },
];

const deliveries = [
  { id: 'TRK1001', orderId: 'ORD1001', buyer: 'Green Mart', product: 'Tomato', quantity: 500, status: 'In Transit', location: 'Coimbatore Distribution Center', destination: 'Green Mart, Coimbatore', partner: 'AgriMove Logistics', expected: '13 September 2026', updated: '11 September 2026, 2:15 PM', timeline: [['Order Placed', '10 Sep, 10:30 AM'], ['Confirmed', '10 Sep, 11:15 AM'], ['Packed', '11 Sep, 8:30 AM'], ['Dispatched', '11 Sep, 2:00 PM'], ['In Transit', 'Currently at Coimbatore Distribution Center']] },
  { id: 'TRK1003', orderId: 'ORD1003', buyer: 'City Supermarket', product: 'Potato', quantity: 750, status: 'Delivered', location: 'Coimbatore', destination: 'City Supermarket, Coimbatore', partner: 'FarmLink Express', expected: '13 September 2026', updated: '13 September 2026, 4:35 PM', deliveredOn: '13 September 2026, 4:35 PM', timeline: [['Order Placed', '8 Sep, 9:10 AM'], ['Confirmed', '8 Sep, 10:00 AM'], ['Packed', '9 Sep, 7:30 AM'], ['Dispatched', '9 Sep, 1:00 PM'], ['In Transit', '10 Sep, 8:00 AM'], ['Out for Delivery', '13 Sep, 10:15 AM'], ['Delivered', '13 Sep, 4:35 PM']] },
  { id: 'TRK1007', orderId: 'ORD1007', buyer: 'Metro Fresh Foods', product: 'Green Chilli', quantity: 2500, status: 'Delayed', location: 'Dindigul Highway Checkpoint', destination: 'Metro Fresh Foods, Madurai', partner: 'AgriMove Logistics', expected: '15 September 2026', updated: '14 September 2026, 8:45 AM', delayReason: 'Heavy traffic / weather delay', timeline: [['Order Placed', '2 Sep, 8:30 AM'], ['Confirmed', '2 Sep, 9:15 AM'], ['Packed', '3 Sep, 7:30 AM'], ['Dispatched', '4 Sep, 2:00 PM'], ['Delayed', '14 Sep, 8:45 AM']] },
];

const emptyProduct = { name: '', category: 'Vegetables', quantity: '', price: '', status: 'Available', location: 'Coimbatore', updated: 'Today', image: '' };
const deliveryClass = (status) => status.toLowerCase().replaceAll(' ', '-');
const formatCurrency = (value) => `₹${value.toLocaleString('en-IN')}`;

const FarmerProfilePage = ({ title = 'Profile', showDelivery = false }) => {
  const [profile, setProfile] = useState(initialProfile);
  const [profileDraft, setProfileDraft] = useState(initialProfile);
  const [products, setProducts] = useState(initialProducts);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [editingProduct, setEditingProduct] = useState(null);
  const [productDraft, setProductDraft] = useState(emptyProduct);
  const [isEditingProfile, setIsEditingProfile] = useState(false);
  const [selectedDelivery, setSelectedDelivery] = useState(null);

  const inventory = useMemo(() => ({
    totalProducts: products.length,
    totalStock: products.reduce((total, product) => total + Number(product.quantity), 0),
    totalValue: products.reduce((total, product) => total + Number(product.quantity) * Number(product.price), 0),
    lowStock: products.filter((product) => product.status === 'Low Stock').length,
  }), [products]);

  const openEditProfile = () => { setProfileDraft(profile); setIsEditingProfile(true); };
  const handleProfileChange = (event) => { const { name, value } = event.target; setProfileDraft((current) => ({ ...current, [name]: value })); };
  const saveProfile = (event) => { event.preventDefault(); setProfile(profileDraft); setIsEditingProfile(false); };
  const openEditProduct = (product) => { setEditingProduct(product); setProductDraft({ ...product, quantity: String(product.quantity), price: String(product.price) }); };
  const handleProductChange = (event) => { const { name, value } = event.target; setProductDraft((current) => ({ ...current, [name]: value })); };
  const saveProduct = (event) => {
    event.preventDefault();
    const nextProduct = { ...productDraft, id: editingProduct.id, quantity: Number(productDraft.quantity), price: Number(productDraft.price) };
    setProducts((current) => current.map((product) => product.id === editingProduct.id ? nextProduct : product));
    setEditingProduct(null);
  };

  const deliverySection = <section className="section-block profile-deliveries"><div className="section-header"><div><h3>Delivery Tracking</h3><p className="muted-text">See whether each order is delivered and track its current location.</p></div><span className="pill-tag"><Truck size={15} /> {deliveries.length} deliveries</span></div><div className="profile-delivery-list">{deliveries.map((delivery) => <article className="profile-delivery-card" key={delivery.id}><div className="profile-delivery-card__top"><div className="profile-delivery-card__title"><span className="profile-delivery-icon"><PackageCheck size={19} /></span><div><strong>{delivery.product}</strong><span>{delivery.buyer} · {delivery.orderId}</span></div></div><span className={`delivery-status delivery-status--${deliveryClass(delivery.status)}`}>{delivery.status}</span></div><div className="profile-delivery-details"><div><span>Quantity</span><strong>{delivery.quantity.toLocaleString()} KG</strong></div><div><span>Current location</span><strong><MapPin size={14} /> {delivery.location}</strong></div><div><span>Expected delivery</span><strong>{delivery.expected}</strong></div><div><span>Tracking ID</span><strong>{delivery.id}</strong></div></div><div className="profile-delivery-card__footer"><span>Updated {delivery.updated}</span><Button onClick={() => setSelectedDelivery(delivery)}><Truck size={15} /> Track Order</Button></div></article>)}</div></section>;

  return (
    <DashboardLayout role="farmer" title={title}>
      {showDelivery ? <div className="profile-page">{deliverySection}</div> : <div className="profile-page">
        <section className="section-block farmer-profile-card"><div className="farmer-profile-card__header"><div className="profile-avatar"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=160&q=80" alt="Dhiya S" /></div><div><span className="eyebrow">Farmer Profile</span><h3>{profile.name}</h3><p className="muted-text">{profile.farmName} · {profile.location}, {profile.state}</p></div><Button variant="secondary" onClick={openEditProfile}><Pencil size={15} /> Edit Profile</Button></div><div className="farmer-profile-fields"><div><span>Phone Number</span><strong>{profile.phone}</strong></div><div><span>Email</span><strong>{profile.email}</strong></div><div><span>Farm Name</span><strong>{profile.farmName}</strong></div><div><span>Farm Location</span><strong>{profile.location}</strong></div><div><span>District</span><strong>{profile.district}</strong></div><div><span>State</span><strong>{profile.state}</strong></div><div><span>Farmer ID</span><strong>{profile.farmerId}</strong></div><div><span>Member Since</span><strong>{profile.memberSince}</strong></div></div></section>
        <section className="profile-products-section"><div className="section-header"><div><h3>My Products</h3><p className="muted-text">Current vegetables and products supplied by {profile.farmName}.</p></div></div><div className="stats-grid profile-inventory-summary"><div className="stat-card"><div className="stat-card__header"><span className="stat-card__dot stat-card__dot--green" />Total Products</div><div className="stat-card__value">{inventory.totalProducts}</div></div><div className="stat-card"><div className="stat-card__header"><span className="stat-card__dot stat-card__dot--teal" />Total Available Stock</div><div className="stat-card__value">{inventory.totalStock.toLocaleString()} KG</div></div><div className="stat-card"><div className="stat-card__header"><span className="stat-card__dot stat-card__dot--dark" />Total Stock Value</div><div className="stat-card__value">{formatCurrency(inventory.totalValue)}</div></div><div className="stat-card"><div className="stat-card__header"><span className="stat-card__dot stat-card__dot--amber" />Low Stock Products</div><div className="stat-card__value">{inventory.lowStock}</div></div></div><div className="profile-product-grid">{products.map((product) => <article className="profile-product-card" key={product.id}><div className="profile-product-card__image"><img src={product.image} alt={product.name} /><span className={`availability-badge availability-badge--${product.status === 'Low Stock' ? 'low-stock' : product.status === 'Out of Stock' ? 'sold-out' : 'available'}`}>{product.status}</span></div><div className="profile-product-card__body"><div className="profile-product-card__title"><div><h4>{product.name}</h4><span>{product.category}</span></div><strong>{formatCurrency(product.price)}<small>/KG</small></strong></div><div className="profile-product-data"><div><span>Available quantity</span><strong>{product.quantity.toLocaleString()} KG</strong></div><div><span>Stock value</span><strong>{formatCurrency(product.quantity * product.price)}</strong></div><div><span>Location</span><strong><MapPin size={13} /> {product.location}</strong></div><div><span>Last updated</span><strong>{product.updated}</strong></div></div><div className="profile-product-actions"><Button variant="secondary" onClick={() => setSelectedProduct(product)}><PackageCheck size={15} /> View Details</Button><Button variant="ghost" onClick={() => openEditProduct(product)}><Edit3 size={15} /> Edit</Button></div></div></article>)}</div></section>
      </div>}

      <Modal isOpen={Boolean(selectedProduct)} onClose={() => setSelectedProduct(null)} title="Product Details">{selectedProduct && <div className="profile-product-modal"><img src={selectedProduct.image} alt={selectedProduct.name} /><div><span className="eyebrow">{selectedProduct.category}</span><h3>{selectedProduct.name}</h3></div><div className="profile-product-detail-list"><div><span>Available quantity</span><strong>{selectedProduct.quantity.toLocaleString()} KG</strong></div><div><span>Price per KG</span><strong>{formatCurrency(selectedProduct.price)}</strong></div><div><span>Total value</span><strong>{formatCurrency(selectedProduct.quantity * selectedProduct.price)}</strong></div><div><span>Availability</span><strong>{selectedProduct.status}</strong></div><div><span>Location</span><strong>{selectedProduct.location}</strong></div><div><span>Last updated</span><strong>{selectedProduct.updated}</strong></div></div></div>}</Modal>
      <Modal isOpen={Boolean(editingProduct)} onClose={() => setEditingProduct(null)} title={`Edit ${editingProduct?.name || 'Product'}`}><form className="profile-product-form" onSubmit={saveProduct}><label>Product name<input required name="name" value={productDraft.name} onChange={handleProductChange} /></label><label>Category<input required name="category" value={productDraft.category} onChange={handleProductChange} /></label><div className="produce-form__row"><label>Available quantity (KG)<input required min="0" type="number" name="quantity" value={productDraft.quantity} onChange={handleProductChange} /></label><label>Price per KG<input required min="0" type="number" name="price" value={productDraft.price} onChange={handleProductChange} /></label></div><div className="produce-form__row"><label>Availability status<select name="status" value={productDraft.status} onChange={handleProductChange}><option>Available</option><option>Low Stock</option><option>Out of Stock</option></select></label><label>Farm/source location<input required name="location" value={productDraft.location} onChange={handleProductChange} /></label></div><div className="produce-form__actions"><Button variant="ghost" onClick={() => setEditingProduct(null)}>Cancel</Button><Button type="submit">Save Product</Button></div></form></Modal>
      <Modal isOpen={isEditingProfile} onClose={() => setIsEditingProfile(false)} title="Edit Profile"><form className="profile-edit-form" onSubmit={saveProfile}><div className="produce-form__row"><label>Name<input required name="name" value={profileDraft.name} onChange={handleProfileChange} /></label><label>Phone<input required name="phone" value={profileDraft.phone} onChange={handleProfileChange} /></label></div><label>Email<input required type="email" name="email" value={profileDraft.email} onChange={handleProfileChange} /></label><label>Farm Name<input required name="farmName" value={profileDraft.farmName} onChange={handleProfileChange} /></label><div className="produce-form__row"><label>Location<input required name="location" value={profileDraft.location} onChange={handleProfileChange} /></label><label>District<input required name="district" value={profileDraft.district} onChange={handleProfileChange} /></label></div><label>State<input required name="state" value={profileDraft.state} onChange={handleProfileChange} /></label><div className="produce-form__actions"><Button variant="ghost" onClick={() => setIsEditingProfile(false)}>Cancel</Button><Button type="submit">Save Changes</Button></div></form></Modal>
      {showDelivery && <Modal isOpen={Boolean(selectedDelivery)} onClose={() => setSelectedDelivery(null)} title="Track Order">{selectedDelivery && <div className="delivery-tracking-modal"><div className="delivery-tracking-heading"><div><span className="eyebrow">{selectedDelivery.id}</span><h3>{selectedDelivery.product} delivery</h3><span className="muted-text">{selectedDelivery.buyer} · {selectedDelivery.orderId}</span></div><span className={`delivery-status delivery-status--${deliveryClass(selectedDelivery.status)}`}>{selectedDelivery.status}</span></div>{selectedDelivery.status === 'Delivered' && <div className="delivery-callout delivery-callout--delivered"><Check size={18} /><div><strong>Delivered</strong><span>Delivered on {selectedDelivery.deliveredOn}</span><span>Delivered to {selectedDelivery.destination}</span></div></div>}{selectedDelivery.status === 'Delayed' && <div className="delivery-callout delivery-callout--delayed"><span className="delivery-warning">!</span><div><strong>Delayed</strong><span>Reason: {selectedDelivery.delayReason}</span><span>New expected delivery: {selectedDelivery.expected}</span></div></div>}<div className="delivery-timeline"><h4>Delivery Timeline</h4>{selectedDelivery.timeline.map(([stage, time], index) => <div className={`timeline-step ${index === selectedDelivery.timeline.length - 1 ? 'timeline-step--current' : ''}`} key={`${stage}-${time}`}><span className="timeline-marker">{index === selectedDelivery.timeline.length - 1 ? <Truck size={14} /> : <Check size={14} />}</span><div><strong>{stage}</strong><span>{time}</span></div></div>)}</div><div className="delivery-detail-grid"><div><span>Tracking ID</span><strong>{selectedDelivery.id}</strong></div><div><span>Order ID</span><strong>{selectedDelivery.orderId}</strong></div><div><span>Current Location</span><strong>{selectedDelivery.location}</strong></div><div><span>Destination</span><strong>{selectedDelivery.destination}</strong></div><div><span>Delivery Partner</span><strong>{selectedDelivery.partner}</strong></div><div><span>Expected Delivery</span><strong>{selectedDelivery.expected}</strong></div><div><span>Last Updated</span><strong>{selectedDelivery.updated}</strong></div></div></div>}</Modal>}
    </DashboardLayout>
  );
};

export default FarmerProfilePage;
